package application.ui.gui;

public class AboutFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 8304157905705554451L;

	public AboutFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jbOk = new javax.swing.JButton();
		jlVersion = new javax.swing.JLabel();
		jtfVersion = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setAlwaysOnTop(true);
		setLocationByPlatform(true);
		setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
		setResizable(false);

		jbOk.setText("Ok");
		jbOk.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jbOkActionPerformed(evt);
			}
		});

		jlVersion.setText("Version");

		jtfVersion.setEditable(false);
		jtfVersion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
		jtfVersion.setText("0.3.0");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addContainerGap()
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jlVersion)
						.addGroup(layout.createSequentialGroup().addGap(52, 52, 52).addComponent(jbOk)))
				.addGap(10, 10, 10)
				.addComponent(jtfVersion, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addGap(28, 28, 28).addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jlVersion)
								.addComponent(jtfVersion, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jbOk)
								.addContainerGap(16, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	@SuppressWarnings("unused")
	private void jbOkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jbOkActionPerformed
		this.dispose();
	}// GEN-LAST:event_jbOkActionPerformed

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new AboutFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbOk;
	private javax.swing.JLabel jlVersion;
	private javax.swing.JTextField jtfVersion;
	// End of variables declaration//GEN-END:variables
}
