package application.ui.gui;

public class EditorFrame extends javax.swing.JFrame {

    public EditorFrame() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspWorkArea = new javax.swing.JSplitPane();
        jspData = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTree();
        jtpEditors = new javax.swing.JTabbedPane();
        jpSystemEditor = new javax.swing.JPanel();
        jpSystem = new javax.swing.JPanel();
        jlSystemName = new javax.swing.JLabel();
        jlSystemType = new javax.swing.JLabel();
        jtfSystemName = new javax.swing.JTextField();
        jcbSystemType = new javax.swing.JComboBox<>();
        jpSystemData = new javax.swing.JPanel();
        jspSystemData = new javax.swing.JSplitPane();
        jpObjectsEditor = new javax.swing.JPanel();
        jlObjects = new javax.swing.JLabel();
        jspObjects = new javax.swing.JScrollPane();
        jtObjects = new javax.swing.JTable();
        jpObjectsButtons = new javax.swing.JPanel();
        jbObjectsInsert = new javax.swing.JButton();
        jbObjectsDelete = new javax.swing.JButton();
        jbObjectsMoveUp = new javax.swing.JButton();
        jbObjectsMoveDown = new javax.swing.JButton();
        jpLinksEditor = new javax.swing.JPanel();
        jlLinks = new javax.swing.JLabel();
        jpLinksButtons = new javax.swing.JPanel();
        jbLinksInsert = new javax.swing.JButton();
        jbLinksDelete = new javax.swing.JButton();
        jbLinksMoveUp = new javax.swing.JButton();
        jbLinksMoveDown = new javax.swing.JButton();
        jspLinks = new javax.swing.JScrollPane();
        jtLinks = new javax.swing.JTable();
        jpNodeEditor = new javax.swing.JPanel();
        jpNode = new javax.swing.JPanel();
        jlNodeId = new javax.swing.JLabel();
        jcbNodeChecked = new javax.swing.JCheckBox();
        jtfNodeId = new javax.swing.JTextField();
        jpEdgesEditor = new javax.swing.JPanel();
        jlEdges = new javax.swing.JLabel();
        jspEdges = new javax.swing.JScrollPane();
        jtEdges = new javax.swing.JTable();
        jpEdgesButtons = new javax.swing.JPanel();
        jbEdgesInsert = new javax.swing.JButton();
        jbEdgesDelete = new javax.swing.JButton();
        jbEdgesUp = new javax.swing.JButton();
        jbEdgesDown = new javax.swing.JButton();
        jpEdgeEditor = new javax.swing.JPanel();
        jpEdge = new javax.swing.JPanel();
        jlEdgeId = new javax.swing.JLabel();
        jlBeginNodeId = new javax.swing.JLabel();
        jlEndNodeId = new javax.swing.JLabel();
        jtfEdgeId = new javax.swing.JTextField();
        jtfBeginNodeId = new javax.swing.JTextField();
        jtfEndNodeId = new javax.swing.JTextField();
        jpOperationEditor = new javax.swing.JPanel();
        jpOperation = new javax.swing.JPanel();
        jlOperationName = new javax.swing.JLabel();
        jtfOperationName = new javax.swing.JTextField();
        jlOperation = new javax.swing.JLabel();
        jpParametersEditor = new javax.swing.JPanel();
        jlParameters = new javax.swing.JLabel();
        jpParametersButtons = new javax.swing.JPanel();
        jbParametersInsert = new javax.swing.JButton();
        jbParametersDelete = new javax.swing.JButton();
        jbParametersUp = new javax.swing.JButton();
        jbParametersDown = new javax.swing.JButton();
        jspParameters = new javax.swing.JScrollPane();
        jtParameters = new javax.swing.JTable();
        jpObjectEditor = new javax.swing.JPanel();
        jpObject = new javax.swing.JPanel();
        jlObjectName = new javax.swing.JLabel();
        jtfObjectName = new javax.swing.JTextField();
        jtfObjectId = new javax.swing.JTextField();
        jlObjectId = new javax.swing.JLabel();
        jpAttributesEditor = new javax.swing.JPanel();
        jlAttributes = new javax.swing.JLabel();
        jspAttributes = new javax.swing.JScrollPane();
        jtAttributes = new javax.swing.JTable();
        jpAttributesButtons = new javax.swing.JPanel();
        jbAttributesInsert = new javax.swing.JButton();
        jbAttributesDelete = new javax.swing.JButton();
        jbAttributesMoveUp = new javax.swing.JButton();
        jbAttributesMoveDown = new javax.swing.JButton();
        jpActionEditor = new javax.swing.JPanel();
        jpActionFunctionEditor = new javax.swing.JPanel();
        jpSystemTransformationEditor = new javax.swing.JPanel();
        jpTransformationsEditor = new javax.swing.JPanel();
        jpTransformationEditor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfEditor"); // NOI18N

        jspData.setPreferredSize(new java.awt.Dimension(150, 275));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Project");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Task Description");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("initialSystem");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-pad");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-pad-sketch");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-plane");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pad");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pad-sketch");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-plane");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket-sketch");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("finalSystem");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("System Transformations");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("2D-Pocket");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("System Template");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("template-object");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Transformations");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("attribute-transformation");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Action");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("action-function");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Node Network");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nodes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("node-id-0000");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("system");
        javax.swing.tree.DefaultMutableTreeNode treeNode6 = new javax.swing.tree.DefaultMutableTreeNode("object-id");
        treeNode5.add(treeNode6);
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Edges");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("edge-id-0000");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Process");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("process-id-0000");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jtData.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jspData.setViewportView(jtData);

        jspWorkArea.setLeftComponent(jspData);

        jlSystemName.setText("name");

        jlSystemType.setText("type");

        jtfSystemName.setText("system-non-unique-name");

        jcbSystemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "initial", "regular", "final" }));
        jcbSystemType.setSelectedIndex(1);

        javax.swing.GroupLayout jpSystemLayout = new javax.swing.GroupLayout(jpSystem);
        jpSystem.setLayout(jpSystemLayout);
        jpSystemLayout.setHorizontalGroup(
            jpSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpSystemLayout.createSequentialGroup()
                        .addComponent(jlSystemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSystemName))
                    .addGroup(jpSystemLayout.createSequentialGroup()
                        .addComponent(jlSystemType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbSystemType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpSystemLayout.setVerticalGroup(
            jpSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSystemName)
                    .addComponent(jtfSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSystemType)
                    .addComponent(jcbSystemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspSystemData.setDividerLocation(150);
        jspSystemData.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jpObjectsEditor.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jlObjects.setText("Objects");

        jtObjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"object-workpiece", "id-workpiece"},
                {"object-workpiece-pad", "id-workpiece-pad"}
            },
            new String [] {
                "name", "id"
            }
        ) {
            Class<?>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspObjects.setViewportView(jtObjects);

        jbObjectsInsert.setText("Insert");

        jbObjectsDelete.setText("Delete");

        jbObjectsMoveUp.setText("Up");

        jbObjectsMoveDown.setText("Down");

        javax.swing.GroupLayout jpObjectsButtonsLayout = new javax.swing.GroupLayout(jpObjectsButtons);
        jpObjectsButtons.setLayout(jpObjectsButtonsLayout);
        jpObjectsButtonsLayout.setHorizontalGroup(
            jpObjectsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpObjectsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbObjectsMoveDown)
                    .addComponent(jbObjectsMoveUp)
                    .addComponent(jbObjectsDelete)
                    .addComponent(jbObjectsInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpObjectsButtonsLayout.setVerticalGroup(
            jpObjectsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbObjectsInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObjectsDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObjectsMoveUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObjectsMoveDown)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpObjectsEditorLayout = new javax.swing.GroupLayout(jpObjectsEditor);
        jpObjectsEditor.setLayout(jpObjectsEditorLayout);
        jpObjectsEditorLayout.setHorizontalGroup(
            jpObjectsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlObjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpObjectsEditorLayout.createSequentialGroup()
                .addComponent(jspObjects, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpObjectsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpObjectsEditorLayout.setVerticalGroup(
            jpObjectsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlObjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpObjectsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpObjectsButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jspSystemData.setTopComponent(jpObjectsEditor);

        jpLinksEditor.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jlLinks.setText("Links");

        jbLinksInsert.setText("Insert");

        jbLinksDelete.setText("Delete");

        jbLinksMoveUp.setText("Up");

        jbLinksMoveDown.setText("Down");

        javax.swing.GroupLayout jpLinksButtonsLayout = new javax.swing.GroupLayout(jpLinksButtons);
        jpLinksButtons.setLayout(jpLinksButtonsLayout);
        jpLinksButtonsLayout.setHorizontalGroup(
            jpLinksButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLinksButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLinksInsert)
                    .addComponent(jbLinksDelete)
                    .addComponent(jbLinksMoveUp)
                    .addComponent(jbLinksMoveDown))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLinksButtonsLayout.setVerticalGroup(
            jpLinksButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLinksInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLinksDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLinksMoveUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLinksMoveDown)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jtLinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"link-has-feature", "id-part", "id-part-pad"},
                {"link-has-feature", "id-workpiece", "id-workpiece-pad"}
            },
            new String [] {
                "name", "id1", "id2"
            }
        ) {
            Class<?>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspLinks.setViewportView(jtLinks);

        javax.swing.GroupLayout jpLinksEditorLayout = new javax.swing.GroupLayout(jpLinksEditor);
        jpLinksEditor.setLayout(jpLinksEditorLayout);
        jpLinksEditorLayout.setHorizontalGroup(
            jpLinksEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLinks)
                .addGap(93, 439, Short.MAX_VALUE))
            .addGroup(jpLinksEditorLayout.createSequentialGroup()
                .addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLinksButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpLinksEditorLayout.setVerticalGroup(
            jpLinksEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLinksEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLinksButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jspSystemData.setRightComponent(jpLinksEditor);

        javax.swing.GroupLayout jpSystemDataLayout = new javax.swing.GroupLayout(jpSystemData);
        jpSystemData.setLayout(jpSystemDataLayout);
        jpSystemDataLayout.setHorizontalGroup(
            jpSystemDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspSystemData)
        );
        jpSystemDataLayout.setVerticalGroup(
            jpSystemDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspSystemData)
        );

        javax.swing.GroupLayout jpSystemEditorLayout = new javax.swing.GroupLayout(jpSystemEditor);
        jpSystemEditor.setLayout(jpSystemEditorLayout);
        jpSystemEditorLayout.setHorizontalGroup(
            jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpSystem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpSystemData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpSystemEditorLayout.setVerticalGroup(
            jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSystemEditorLayout.createSequentialGroup()
                .addComponent(jpSystem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpSystemData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEditors.addTab("System", jpSystemEditor);

        jlNodeId.setText("id");

        jcbNodeChecked.setText("checked");

        jtfNodeId.setText("unique-node-id");

        javax.swing.GroupLayout jpNodeLayout = new javax.swing.GroupLayout(jpNode);
        jpNode.setLayout(jpNodeLayout);
        jpNodeLayout.setHorizontalGroup(
            jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNodeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlNodeId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpNodeLayout.createSequentialGroup()
                        .addComponent(jcbNodeChecked)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtfNodeId, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpNodeLayout.setVerticalGroup(
            jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNodeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpNodeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNodeId)
                    .addComponent(jtfNodeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbNodeChecked))
        );

        jlEdges.setText("Edges");

        jtEdges.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"unique-edge-id", "another-unique-node-id"},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "id", "endNodeId"
            }
        ) {
            Class<?>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspEdges.setViewportView(jtEdges);

        jbEdgesInsert.setText("Insert");

        jbEdgesDelete.setText("Delete");

        jbEdgesUp.setText("Up");

        jbEdgesDown.setText("Down");

        javax.swing.GroupLayout jpEdgesButtonsLayout = new javax.swing.GroupLayout(jpEdgesButtons);
        jpEdgesButtons.setLayout(jpEdgesButtonsLayout);
        jpEdgesButtonsLayout.setHorizontalGroup(
            jpEdgesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdgesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEdgesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbEdgesInsert)
                    .addComponent(jbEdgesDelete)
                    .addComponent(jbEdgesUp)
                    .addComponent(jbEdgesDown))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpEdgesButtonsLayout.setVerticalGroup(
            jpEdgesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdgesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbEdgesInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEdgesDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEdgesUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbEdgesDown)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpEdgesEditorLayout = new javax.swing.GroupLayout(jpEdgesEditor);
        jpEdgesEditor.setLayout(jpEdgesEditorLayout);
        jpEdgesEditorLayout.setHorizontalGroup(
            jpEdgesEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdgesEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEdges)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpEdgesEditorLayout.createSequentialGroup()
                .addComponent(jspEdges, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEdgesButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpEdgesEditorLayout.setVerticalGroup(
            jpEdgesEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdgesEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlEdges)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEdgesEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpEdgesButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspEdges, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpNodeEditorLayout = new javax.swing.GroupLayout(jpNodeEditor);
        jpNodeEditor.setLayout(jpNodeEditorLayout);
        jpNodeEditorLayout.setHorizontalGroup(
            jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpNode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpEdgesEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpNodeEditorLayout.setVerticalGroup(
            jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpNodeEditorLayout.createSequentialGroup()
                .addComponent(jpNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpEdgesEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEditors.addTab("Node", jpNodeEditor);

        jlEdgeId.setText("id");

        jlBeginNodeId.setText("beginNodeId");

        jlEndNodeId.setText("endNodeId");

        jtfEdgeId.setText("edge-unique-id");

        jtfBeginNodeId.setText("node-unique-id-1");

        jtfEndNodeId.setText("node-unique-id-2");

        javax.swing.GroupLayout jpEdgeLayout = new javax.swing.GroupLayout(jpEdge);
        jpEdge.setLayout(jpEdgeLayout);
        jpEdgeLayout.setHorizontalGroup(
            jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlBeginNodeId)
                    .addComponent(jlEndNodeId)
                    .addComponent(jlEdgeId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfEdgeId)
                    .addComponent(jtfEndNodeId, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addComponent(jtfBeginNodeId))
                .addContainerGap())
        );
        jpEdgeLayout.setVerticalGroup(
            jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEdgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEdgeId)
                    .addComponent(jtfEdgeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfBeginNodeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlBeginNodeId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfEndNodeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlEndNodeId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpOperationEditor.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jlOperationName.setText("name");

        jtfOperationName.setText("operation-name");

        javax.swing.GroupLayout jpOperationLayout = new javax.swing.GroupLayout(jpOperation);
        jpOperation.setLayout(jpOperationLayout);
        jpOperationLayout.setHorizontalGroup(
            jpOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOperationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlOperationName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfOperationName)
                .addContainerGap())
        );
        jpOperationLayout.setVerticalGroup(
            jpOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOperationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpOperationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlOperationName)
                    .addComponent(jtfOperationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlOperation.setText("Operation");

        jlParameters.setText("Parameters");

        jbParametersInsert.setText("Insert");

        jbParametersDelete.setText("Delete");

        jbParametersUp.setText("Up");

        jbParametersDown.setText("Down");

        javax.swing.GroupLayout jpParametersButtonsLayout = new javax.swing.GroupLayout(jpParametersButtons);
        jpParametersButtons.setLayout(jpParametersButtonsLayout);
        jpParametersButtonsLayout.setHorizontalGroup(
            jpParametersButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParametersButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpParametersButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbParametersDelete)
                    .addComponent(jbParametersUp)
                    .addComponent(jbParametersDown))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpParametersButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbParametersInsert)
                .addContainerGap())
        );
        jpParametersButtonsLayout.setVerticalGroup(
            jpParametersButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParametersButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbParametersInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbParametersDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbParametersUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbParametersDown)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtParameters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"parameter-diameter", "2"}
            },
            new String [] {
                "name", "value"
            }
        ) {
            Class<?>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspParameters.setViewportView(jtParameters);

        javax.swing.GroupLayout jpParametersEditorLayout = new javax.swing.GroupLayout(jpParametersEditor);
        jpParametersEditor.setLayout(jpParametersEditorLayout);
        jpParametersEditorLayout.setHorizontalGroup(
            jpParametersEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParametersEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlParameters)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpParametersEditorLayout.createSequentialGroup()
                .addComponent(jspParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpParametersButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpParametersEditorLayout.setVerticalGroup(
            jpParametersEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpParametersEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlParameters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpParametersEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpParametersButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspParameters, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpOperationEditorLayout = new javax.swing.GroupLayout(jpOperationEditor);
        jpOperationEditor.setLayout(jpOperationEditorLayout);
        jpOperationEditorLayout.setHorizontalGroup(
            jpOperationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOperationEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlOperation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jpOperation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpParametersEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpOperationEditorLayout.setVerticalGroup(
            jpOperationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpOperationEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpOperation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpParametersEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpEdgeEditorLayout = new javax.swing.GroupLayout(jpEdgeEditor);
        jpEdgeEditor.setLayout(jpEdgeEditorLayout);
        jpEdgeEditorLayout.setHorizontalGroup(
            jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpEdge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpOperationEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpEdgeEditorLayout.setVerticalGroup(
            jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEdgeEditorLayout.createSequentialGroup()
                .addComponent(jpEdge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpOperationEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEditors.addTab("Edge", jpEdgeEditor);

        jlObjectName.setText("name");

        jtfObjectName.setText("object-workpiece");

        jtfObjectId.setText("id-workpiece");

        jlObjectId.setText("id");

        javax.swing.GroupLayout jpObjectLayout = new javax.swing.GroupLayout(jpObject);
        jpObject.setLayout(jpObjectLayout);
        jpObjectLayout.setHorizontalGroup(
            jpObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpObjectLayout.createSequentialGroup()
                        .addComponent(jlObjectName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jpObjectLayout.createSequentialGroup()
                        .addComponent(jlObjectId)
                        .addGap(26, 26, 26)))
                .addGroup(jpObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfObjectName, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                    .addComponent(jtfObjectId))
                .addContainerGap())
        );
        jpObjectLayout.setVerticalGroup(
            jpObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlObjectName)
                    .addComponent(jtfObjectName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpObjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfObjectId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlObjectId))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpAttributesEditor.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        jlAttributes.setText("Attributes");

        jtAttributes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"attribute-feature", "boolean", "true"}
            },
            new String [] {
                "name", "type", "value"
            }
        ) {
            Class<?>[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspAttributes.setViewportView(jtAttributes);

        jbAttributesInsert.setText("Insert");

        jbAttributesDelete.setText("Delete");

        jbAttributesMoveUp.setText("Up");

        jbAttributesMoveDown.setText("Down");

        javax.swing.GroupLayout jpAttributesButtonsLayout = new javax.swing.GroupLayout(jpAttributesButtons);
        jpAttributesButtons.setLayout(jpAttributesButtonsLayout);
        jpAttributesButtonsLayout.setHorizontalGroup(
            jpAttributesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAttributesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAttributesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbAttributesInsert)
                    .addComponent(jbAttributesDelete)
                    .addComponent(jbAttributesMoveUp)
                    .addComponent(jbAttributesMoveDown))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpAttributesButtonsLayout.setVerticalGroup(
            jpAttributesButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAttributesButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbAttributesInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAttributesDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAttributesMoveUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbAttributesMoveDown)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpAttributesEditorLayout = new javax.swing.GroupLayout(jpAttributesEditor);
        jpAttributesEditor.setLayout(jpAttributesEditorLayout);
        jpAttributesEditorLayout.setHorizontalGroup(
            jpAttributesEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAttributesEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAttributes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpAttributesEditorLayout.createSequentialGroup()
                .addComponent(jspAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAttributesButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpAttributesEditorLayout.setVerticalGroup(
            jpAttributesEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAttributesEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlAttributes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpAttributesEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpAttributesButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspAttributes, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jpObjectEditorLayout = new javax.swing.GroupLayout(jpObjectEditor);
        jpObjectEditor.setLayout(jpObjectEditorLayout);
        jpObjectEditorLayout.setHorizontalGroup(
            jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpObject, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpAttributesEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpObjectEditorLayout.setVerticalGroup(
            jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectEditorLayout.createSequentialGroup()
                .addComponent(jpObject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpAttributesEditor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEditors.addTab("Object", jpObjectEditor);

        javax.swing.GroupLayout jpActionEditorLayout = new javax.swing.GroupLayout(jpActionEditor);
        jpActionEditor.setLayout(jpActionEditorLayout);
        jpActionEditorLayout.setHorizontalGroup(
            jpActionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jpActionEditorLayout.setVerticalGroup(
            jpActionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Action", jpActionEditor);

        javax.swing.GroupLayout jpActionFunctionEditorLayout = new javax.swing.GroupLayout(jpActionFunctionEditor);
        jpActionFunctionEditor.setLayout(jpActionFunctionEditorLayout);
        jpActionFunctionEditorLayout.setHorizontalGroup(
            jpActionFunctionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jpActionFunctionEditorLayout.setVerticalGroup(
            jpActionFunctionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Action Function", jpActionFunctionEditor);

        javax.swing.GroupLayout jpSystemTransformationEditorLayout = new javax.swing.GroupLayout(jpSystemTransformationEditor);
        jpSystemTransformationEditor.setLayout(jpSystemTransformationEditorLayout);
        jpSystemTransformationEditorLayout.setHorizontalGroup(
            jpSystemTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jpSystemTransformationEditorLayout.setVerticalGroup(
            jpSystemTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jtpEditors.addTab("System Transformation", jpSystemTransformationEditor);

        javax.swing.GroupLayout jpTransformationsEditorLayout = new javax.swing.GroupLayout(jpTransformationsEditor);
        jpTransformationsEditor.setLayout(jpTransformationsEditorLayout);
        jpTransformationsEditorLayout.setHorizontalGroup(
            jpTransformationsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jpTransformationsEditorLayout.setVerticalGroup(
            jpTransformationsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Transformations", jpTransformationsEditor);

        javax.swing.GroupLayout jpTransformationEditorLayout = new javax.swing.GroupLayout(jpTransformationEditor);
        jpTransformationEditor.setLayout(jpTransformationEditorLayout);
        jpTransformationEditorLayout.setHorizontalGroup(
            jpTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );
        jpTransformationEditorLayout.setVerticalGroup(
            jpTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 541, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Transformation", jpTransformationEditor);

        jspWorkArea.setRightComponent(jtpEditors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspWorkArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspWorkArea)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
		@Override
	    public void run() {
		new EditorFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAttributesDelete;
    private javax.swing.JButton jbAttributesInsert;
    private javax.swing.JButton jbAttributesMoveDown;
    private javax.swing.JButton jbAttributesMoveUp;
    private javax.swing.JButton jbEdgesDelete;
    private javax.swing.JButton jbEdgesDown;
    private javax.swing.JButton jbEdgesInsert;
    private javax.swing.JButton jbEdgesUp;
    private javax.swing.JButton jbLinksDelete;
    private javax.swing.JButton jbLinksInsert;
    private javax.swing.JButton jbLinksMoveDown;
    private javax.swing.JButton jbLinksMoveUp;
    private javax.swing.JButton jbObjectsDelete;
    private javax.swing.JButton jbObjectsInsert;
    private javax.swing.JButton jbObjectsMoveDown;
    private javax.swing.JButton jbObjectsMoveUp;
    private javax.swing.JButton jbParametersDelete;
    private javax.swing.JButton jbParametersDown;
    private javax.swing.JButton jbParametersInsert;
    private javax.swing.JButton jbParametersUp;
    private javax.swing.JCheckBox jcbNodeChecked;
    private javax.swing.JComboBox<String> jcbSystemType;
    private javax.swing.JLabel jlAttributes;
    private javax.swing.JLabel jlBeginNodeId;
    private javax.swing.JLabel jlEdgeId;
    private javax.swing.JLabel jlEdges;
    private javax.swing.JLabel jlEndNodeId;
    private javax.swing.JLabel jlLinks;
    private javax.swing.JLabel jlNodeId;
    private javax.swing.JLabel jlObjectId;
    private javax.swing.JLabel jlObjectName;
    private javax.swing.JLabel jlObjects;
    private javax.swing.JLabel jlOperation;
    private javax.swing.JLabel jlOperationName;
    private javax.swing.JLabel jlParameters;
    private javax.swing.JLabel jlSystemName;
    private javax.swing.JLabel jlSystemType;
    private javax.swing.JPanel jpActionEditor;
    private javax.swing.JPanel jpActionFunctionEditor;
    private javax.swing.JPanel jpAttributesButtons;
    private javax.swing.JPanel jpAttributesEditor;
    private javax.swing.JPanel jpEdge;
    private javax.swing.JPanel jpEdgeEditor;
    private javax.swing.JPanel jpEdgesButtons;
    private javax.swing.JPanel jpEdgesEditor;
    private javax.swing.JPanel jpLinksButtons;
    private javax.swing.JPanel jpLinksEditor;
    private javax.swing.JPanel jpNode;
    private javax.swing.JPanel jpNodeEditor;
    private javax.swing.JPanel jpObject;
    private javax.swing.JPanel jpObjectEditor;
    private javax.swing.JPanel jpObjectsButtons;
    private javax.swing.JPanel jpObjectsEditor;
    private javax.swing.JPanel jpOperation;
    private javax.swing.JPanel jpOperationEditor;
    private javax.swing.JPanel jpParametersButtons;
    private javax.swing.JPanel jpParametersEditor;
    private javax.swing.JPanel jpSystem;
    private javax.swing.JPanel jpSystemData;
    private javax.swing.JPanel jpSystemEditor;
    private javax.swing.JPanel jpSystemTransformationEditor;
    private javax.swing.JPanel jpTransformationEditor;
    private javax.swing.JPanel jpTransformationsEditor;
    private javax.swing.JScrollPane jspAttributes;
    private javax.swing.JScrollPane jspData;
    private javax.swing.JScrollPane jspEdges;
    private javax.swing.JScrollPane jspLinks;
    private javax.swing.JScrollPane jspObjects;
    private javax.swing.JScrollPane jspParameters;
    private javax.swing.JSplitPane jspSystemData;
    private javax.swing.JSplitPane jspWorkArea;
    private javax.swing.JTable jtAttributes;
    private javax.swing.JTree jtData;
    private javax.swing.JTable jtEdges;
    private javax.swing.JTable jtLinks;
    private javax.swing.JTable jtObjects;
    private javax.swing.JTable jtParameters;
    private javax.swing.JTextField jtfBeginNodeId;
    private javax.swing.JTextField jtfEdgeId;
    private javax.swing.JTextField jtfEndNodeId;
    private javax.swing.JTextField jtfNodeId;
    private javax.swing.JTextField jtfObjectId;
    private javax.swing.JTextField jtfObjectName;
    private javax.swing.JTextField jtfOperationName;
    private javax.swing.JTextField jtfSystemName;
    private javax.swing.JTabbedPane jtpEditors;
    // End of variables declaration//GEN-END:variables
}
