/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package application.ui.gui;

/**
 *
 * @author kinnd
 */
public class EditorFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditorFrame
     */
    public EditorFrame() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jspWorkArea = new javax.swing.JSplitPane();
        jspData = new javax.swing.JScrollPane();
        jtData = new javax.swing.JTree();
        jtpEditors = new javax.swing.JTabbedPane();
        jpSystemEditor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jlSystemName = new javax.swing.JLabel();
        jlSystemType = new javax.swing.JLabel();
        jtfSystemName = new javax.swing.JTextField();
        jcbSystemType = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jpObjectsEditor = new javax.swing.JPanel();
        jlObjects = new javax.swing.JLabel();
        jspObjects = new javax.swing.JScrollPane();
        jtObjects = new javax.swing.JTable();
        jpObjectsButtons = new javax.swing.JPanel();
        jbObjectsInsert = new javax.swing.JButton();
        jbObjectsDelete = new javax.swing.JButton();
        jbObjectsMoveUp = new javax.swing.JButton();
        jbObjectsMoveDown = new javax.swing.JButton();
        jpLinksEditor = new javax.swing.JPanel();
        jlLinks = new javax.swing.JLabel();
        jpLinksButtons = new javax.swing.JPanel();
        jbLinksInsert = new javax.swing.JButton();
        jbLinksDelete = new javax.swing.JButton();
        jbLinksMoveUp = new javax.swing.JButton();
        jbLinksMoveDown = new javax.swing.JButton();
        jspLinks = new javax.swing.JScrollPane();
        jtLinks = new javax.swing.JTable();
        jpNodeEditor = new javax.swing.JPanel();
        jpEdgeEditor = new javax.swing.JPanel();
        jpObjectEditor = new javax.swing.JPanel();
        jpActionEditor = new javax.swing.JPanel();
        jpActionFunctionEditor = new javax.swing.JPanel();
        jpSystemTransformationEditor = new javax.swing.JPanel();
        jpTransformationsEditor = new javax.swing.JPanel();
        jpTransformationEditor = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("jfEditor"); // NOI18N

        jspData.setPreferredSize(new java.awt.Dimension(150, 275));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Project");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Task Description");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("initialSystem");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-pad");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-pad-sketch");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-plane");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pad");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pad-sketch");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-plane");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket-sketch");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("finalSystem");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("System Transformations");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("2D-Pocket");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("System Template");
        javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("template-object");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Transformations");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("attribute-transformation");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Action");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("action-function");
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Node Network");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nodes");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("node-id-0000");
        treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("system");
        javax.swing.tree.DefaultMutableTreeNode treeNode6 = new javax.swing.tree.DefaultMutableTreeNode("object-id");
        treeNode5.add(treeNode6);
        treeNode4.add(treeNode5);
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Edges");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("edge-id-0000");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Process");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("process-id-0000");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jtData.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jspData.setViewportView(jtData);

        jspWorkArea.setLeftComponent(jspData);

        jlSystemName.setText("name");

        jlSystemType.setText("type");

        jtfSystemName.setText("system-non-unique-name");

        jcbSystemType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "initial", "regular", "final" }));
        jcbSystemType.setSelectedIndex(1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlSystemName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfSystemName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlSystemType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jcbSystemType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSystemName)
                    .addComponent(jtfSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlSystemType)
                    .addComponent(jcbSystemType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jpObjectsEditor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlObjects.setText("Objects");

        jtObjects.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"object-workpiece", "id-workpiece"},
                {"object-workpiece-pad", "id-workpiece-pad"}
            },
            new String [] {
                "name", "id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspObjects.setViewportView(jtObjects);

        jbObjectsInsert.setText("Insert");

        jbObjectsDelete.setText("Delete");

        jbObjectsMoveUp.setText("Up");

        jbObjectsMoveDown.setText("Down");

        javax.swing.GroupLayout jpObjectsButtonsLayout = new javax.swing.GroupLayout(jpObjectsButtons);
        jpObjectsButtons.setLayout(jpObjectsButtonsLayout);
        jpObjectsButtonsLayout.setHorizontalGroup(
            jpObjectsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpObjectsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbObjectsMoveDown)
                    .addComponent(jbObjectsMoveUp)
                    .addComponent(jbObjectsDelete)
                    .addComponent(jbObjectsInsert))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpObjectsButtonsLayout.setVerticalGroup(
            jpObjectsButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbObjectsInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObjectsDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObjectsMoveUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbObjectsMoveDown)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpObjectsEditorLayout = new javax.swing.GroupLayout(jpObjectsEditor);
        jpObjectsEditor.setLayout(jpObjectsEditorLayout);
        jpObjectsEditorLayout.setHorizontalGroup(
            jpObjectsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlObjects)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpObjectsEditorLayout.createSequentialGroup()
                .addComponent(jspObjects, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpObjectsButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpObjectsEditorLayout.setVerticalGroup(
            jpObjectsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpObjectsEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlObjects)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpObjectsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpObjectsButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jSplitPane1.setTopComponent(jpObjectsEditor);

        jpLinksEditor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jlLinks.setText("Links");

        jbLinksInsert.setText("Insert");

        jbLinksDelete.setText("Delete");

        jbLinksMoveUp.setText("Up");

        jbLinksMoveDown.setText("Down");

        javax.swing.GroupLayout jpLinksButtonsLayout = new javax.swing.GroupLayout(jpLinksButtons);
        jpLinksButtons.setLayout(jpLinksButtonsLayout);
        jpLinksButtonsLayout.setHorizontalGroup(
            jpLinksButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpLinksButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbLinksInsert)
                    .addComponent(jbLinksDelete)
                    .addComponent(jbLinksMoveUp)
                    .addComponent(jbLinksMoveDown))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpLinksButtonsLayout.setVerticalGroup(
            jpLinksButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbLinksInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLinksDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLinksMoveUp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbLinksMoveDown)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        jtLinks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"link-has-feature", "id-part", "id-part-pad"},
                {"link-has-feature", "id-workpiece", "id-workpiece-pad"}
            },
            new String [] {
                "name", "id1", "id2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jspLinks.setViewportView(jtLinks);

        javax.swing.GroupLayout jpLinksEditorLayout = new javax.swing.GroupLayout(jpLinksEditor);
        jpLinksEditor.setLayout(jpLinksEditorLayout);
        jpLinksEditorLayout.setHorizontalGroup(
            jpLinksEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLinks)
                .addGap(93, 424, Short.MAX_VALUE))
            .addGroup(jpLinksEditorLayout.createSequentialGroup()
                .addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpLinksButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpLinksEditorLayout.setVerticalGroup(
            jpLinksEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLinksEditorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlLinks)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpLinksEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpLinksButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
        );

        jSplitPane1.setRightComponent(jpLinksEditor);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        javax.swing.GroupLayout jpSystemEditorLayout = new javax.swing.GroupLayout(jpSystemEditor);
        jpSystemEditor.setLayout(jpSystemEditorLayout);
        jpSystemEditorLayout.setHorizontalGroup(
            jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpSystemEditorLayout.setVerticalGroup(
            jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSystemEditorLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtpEditors.addTab("System", jpSystemEditor);

        javax.swing.GroupLayout jpNodeEditorLayout = new javax.swing.GroupLayout(jpNodeEditor);
        jpNodeEditor.setLayout(jpNodeEditorLayout);
        jpNodeEditorLayout.setHorizontalGroup(
            jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpNodeEditorLayout.setVerticalGroup(
            jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Node", jpNodeEditor);

        javax.swing.GroupLayout jpEdgeEditorLayout = new javax.swing.GroupLayout(jpEdgeEditor);
        jpEdgeEditor.setLayout(jpEdgeEditorLayout);
        jpEdgeEditorLayout.setHorizontalGroup(
            jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpEdgeEditorLayout.setVerticalGroup(
            jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Edge", jpEdgeEditor);

        javax.swing.GroupLayout jpObjectEditorLayout = new javax.swing.GroupLayout(jpObjectEditor);
        jpObjectEditor.setLayout(jpObjectEditorLayout);
        jpObjectEditorLayout.setHorizontalGroup(
            jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpObjectEditorLayout.setVerticalGroup(
            jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Object", jpObjectEditor);

        javax.swing.GroupLayout jpActionEditorLayout = new javax.swing.GroupLayout(jpActionEditor);
        jpActionEditor.setLayout(jpActionEditorLayout);
        jpActionEditorLayout.setHorizontalGroup(
            jpActionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpActionEditorLayout.setVerticalGroup(
            jpActionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Action", jpActionEditor);

        javax.swing.GroupLayout jpActionFunctionEditorLayout = new javax.swing.GroupLayout(jpActionFunctionEditor);
        jpActionFunctionEditor.setLayout(jpActionFunctionEditorLayout);
        jpActionFunctionEditorLayout.setHorizontalGroup(
            jpActionFunctionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpActionFunctionEditorLayout.setVerticalGroup(
            jpActionFunctionEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Action Function", jpActionFunctionEditor);

        javax.swing.GroupLayout jpSystemTransformationEditorLayout = new javax.swing.GroupLayout(jpSystemTransformationEditor);
        jpSystemTransformationEditor.setLayout(jpSystemTransformationEditorLayout);
        jpSystemTransformationEditorLayout.setHorizontalGroup(
            jpSystemTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpSystemTransformationEditorLayout.setVerticalGroup(
            jpSystemTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("System Transformation", jpSystemTransformationEditor);

        javax.swing.GroupLayout jpTransformationsEditorLayout = new javax.swing.GroupLayout(jpTransformationsEditor);
        jpTransformationsEditor.setLayout(jpTransformationsEditorLayout);
        jpTransformationsEditorLayout.setHorizontalGroup(
            jpTransformationsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpTransformationsEditorLayout.setVerticalGroup(
            jpTransformationsEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Transformations", jpTransformationsEditor);

        javax.swing.GroupLayout jpTransformationEditorLayout = new javax.swing.GroupLayout(jpTransformationEditor);
        jpTransformationEditor.setLayout(jpTransformationEditorLayout);
        jpTransformationEditorLayout.setHorizontalGroup(
            jpTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );
        jpTransformationEditorLayout.setVerticalGroup(
            jpTransformationEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        jtpEditors.addTab("Transformation", jpTransformationEditor);

        jspWorkArea.setRightComponent(jtpEditors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspWorkArea)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jspWorkArea)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(EditorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
		@Override
	    public void run() {
		new EditorFrame().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbLinksDelete;
    private javax.swing.JButton jbLinksInsert;
    private javax.swing.JButton jbLinksMoveDown;
    private javax.swing.JButton jbLinksMoveUp;
    private javax.swing.JButton jbObjectsDelete;
    private javax.swing.JButton jbObjectsInsert;
    private javax.swing.JButton jbObjectsMoveDown;
    private javax.swing.JButton jbObjectsMoveUp;
    private javax.swing.JComboBox<String> jcbSystemType;
    private javax.swing.JLabel jlLinks;
    private javax.swing.JLabel jlObjects;
    private javax.swing.JLabel jlSystemName;
    private javax.swing.JLabel jlSystemType;
    private javax.swing.JPanel jpActionEditor;
    private javax.swing.JPanel jpActionFunctionEditor;
    private javax.swing.JPanel jpEdgeEditor;
    private javax.swing.JPanel jpLinksButtons;
    private javax.swing.JPanel jpLinksEditor;
    private javax.swing.JPanel jpNodeEditor;
    private javax.swing.JPanel jpObjectEditor;
    private javax.swing.JPanel jpObjectsButtons;
    private javax.swing.JPanel jpObjectsEditor;
    private javax.swing.JPanel jpSystemEditor;
    private javax.swing.JPanel jpSystemTransformationEditor;
    private javax.swing.JPanel jpTransformationEditor;
    private javax.swing.JPanel jpTransformationsEditor;
    private javax.swing.JScrollPane jspData;
    private javax.swing.JScrollPane jspLinks;
    private javax.swing.JScrollPane jspObjects;
    private javax.swing.JSplitPane jspWorkArea;
    private javax.swing.JTree jtData;
    private javax.swing.JTable jtLinks;
    private javax.swing.JTable jtObjects;
    private javax.swing.JTextField jtfSystemName;
    private javax.swing.JTabbedPane jtpEditors;
    // End of variables declaration//GEN-END:variables
}
