package application.ui.gui;

import application.Application;
import application.event.CommandStatusEvent;
import application.event.UserMessageEvent;
import application.ui.UserInterface;

import java.util.logging.Level;
import java.util.logging.Logger;

public class MainViewFrame extends javax.swing.JFrame implements UserInterface {

	private static final long serialVersionUID = 514069652804189117L;

	public MainViewFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		jScrollPane1 = new javax.swing.JScrollPane();
		jtaLog = new javax.swing.JTextArea();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jmiOptions = new javax.swing.JMenuItem();
		jmiExit = new javax.swing.JMenuItem();
		jMenu2 = new javax.swing.JMenu();
		jmiConvert = new javax.swing.JMenuItem();
		jmiNewTransformations = new javax.swing.JMenuItem();
		jmiNewTask = new javax.swing.JMenuItem();
		jmiPlan = new javax.swing.JMenuItem();
		jmiVerify = new javax.swing.JMenuItem();
		jMenu3 = new javax.swing.JMenu();
		jmiUsage = new javax.swing.JMenuItem();
		jmiAbout = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Process Engineering");
		setName("jfMainView"); // NOI18N

		jtaLog.setEditable(false);
		jtaLog.setColumns(20);
		jtaLog.setRows(5);
		jScrollPane1.setViewportView(jtaLog);

		jMenu1.setText("Application");

		jmiOptions.setText("Options");
		jmiOptions.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiOptionsActionPerformed(evt);
			}
		});
		jMenu1.add(jmiOptions);

		jmiExit.setText("Exit");
		jmiExit.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiExitActionPerformed(evt);
			}
		});
		jMenu1.add(jmiExit);

		jMenuBar1.add(jMenu1);

		jMenu2.setText("Commands");

		jmiConvert.setText("Convert");
		jmiConvert.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiConvertActionPerformed(evt);
			}
		});
		jMenu2.add(jmiConvert);

		jmiNewTransformations.setText("New Transformations");
		jmiNewTransformations.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiNewTransformationsActionPerformed(evt);
			}
		});
		jMenu2.add(jmiNewTransformations);

		jmiNewTask.setText("New Task");
		jmiNewTask.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiNewTaskActionPerformed(evt);
			}
		});
		jMenu2.add(jmiNewTask);

		jmiPlan.setText("Plan");
		jmiPlan.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiPlanActionPerformed(evt);
			}
		});
		jMenu2.add(jmiPlan);

		jmiVerify.setText("Verify");
		jmiVerify.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiVerifyActionPerformed(evt);
			}
		});
		jMenu2.add(jmiVerify);

		jMenuBar1.add(jMenu2);

		jMenu3.setText("Help");

		jmiUsage.setText("Usage");
		jmiUsage.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiUsageActionPerformed(evt);
			}
		});
		jMenu3.add(jmiUsage);

		jmiAbout.setText("About");
		jmiAbout.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jmiAboutActionPerformed(evt);
			}
		});
		jMenu3.add(jmiAbout);

		jMenuBar1.add(jMenu3);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 219,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	@SuppressWarnings("unused")
	private void jmiOptionsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiOptionsActionPerformed
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				OptionsFrame optionsFrame = new OptionsFrame();
				optionsFrame.setApplication(application);
				optionsFrame.updateComponents();
				optionsFrame.setVisible(true);
			}
		});
	}// GEN-LAST:event_jmiOptionsActionPerformed

	@SuppressWarnings("unused")
	private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiExitActionPerformed
		this.dispose();
	}// GEN-LAST:event_jmiExitActionPerformed

	@SuppressWarnings("unused")
	private void jmiPlanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiPlanActionPerformed
		application.plan();
	}// GEN-LAST:event_jmiPlanActionPerformed

	@SuppressWarnings("unused")
	private void jmiVerifyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiVerifyActionPerformed
		application.verify();
	}// GEN-LAST:event_jmiVerifyActionPerformed

	@SuppressWarnings("unused")
	private void jmiNewTaskActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiNewTaskActionPerformed
		application.newTaskDescription();
	}// GEN-LAST:event_jmiNewTaskActionPerformed

	@SuppressWarnings("unused")
	private void jmiNewTransformationsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiNewTransformationsActionPerformed
		application.newSystemTransformations();
	}// GEN-LAST:event_jmiNewTransformationsActionPerformed

	@SuppressWarnings("unused")
	private void jmiConvertActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiConvertActionPerformed
		application.convert();
	}// GEN-LAST:event_jmiConvertActionPerformed

	@SuppressWarnings("unused")
	private void jmiUsageActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiUsageActionPerformed
		try {
			application.usageHelp();
		} catch (Exception ex) {
			Logger.getLogger(MainViewFrame.class.getName()).log(Level.SEVERE, null, ex);
		}
	}// GEN-LAST:event_jmiUsageActionPerformed

	@SuppressWarnings("unused")
	private void jmiAboutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jmiAboutActionPerformed
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new AboutFrame().setVisible(true);
			}
		});
	}// GEN-LAST:event_jmiAboutActionPerformed

	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new MainViewFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JMenuItem jmiAbout;
	private javax.swing.JMenuItem jmiConvert;
	private javax.swing.JMenuItem jmiExit;
	private javax.swing.JMenuItem jmiNewTask;
	private javax.swing.JMenuItem jmiNewTransformations;
	private javax.swing.JMenuItem jmiOptions;
	private javax.swing.JMenuItem jmiPlan;
	private javax.swing.JMenuItem jmiUsage;
	private javax.swing.JMenuItem jmiVerify;
	private javax.swing.JTextArea jtaLog;
	// End of variables declaration//GEN-END:variables

	private Application application = new Application();

	@Override
	public void setApplication(Application application) {
		this.application = application;
	}

	@Override
	public void notifyUserMessage(UserMessageEvent event) {
		jtaLog.append(event.message);
		jtaLog.append("\n");
	}

	@Override
	public void notifyCommandStatus(CommandStatusEvent event) {
		jtaLog.append(event.message);
		jtaLog.append("\n");
	}

	public static void initializeLookAndFeel() throws Exception {
		for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				javax.swing.UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	}

	@Override
	public void run() throws Exception {
		initializeLookAndFeel();
		setVisible(true);
	}
}
