package application.ui.gui;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

public class NodeNetworkEditorFrame extends javax.swing.JFrame {

	// TODO (2022-08-28 #68): включить проверку copy-paste
	// CPD-OFF

	private static final long serialVersionUID = 2512211446680748460L;

	public NodeNetworkEditorFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jrbgSystemTypes = new javax.swing.ButtonGroup();
		jspNodeNetwork = new javax.swing.JScrollPane();
		jtNodeNetwork = new javax.swing.JTree();
		jtpEditors = new javax.swing.JTabbedPane();
		jpNodeEditor = new javax.swing.JPanel();
		jlNodeId = new javax.swing.JLabel();
		jtfNodeId = new javax.swing.JTextField();
		jcbChecked = new javax.swing.JCheckBox();
		jlEdges = new javax.swing.JLabel();
		jspEdges = new javax.swing.JScrollPane();
		jtEdges = new javax.swing.JTable();
		jbEdgesInsert = new javax.swing.JButton();
		jbEdgesDelete = new javax.swing.JButton();
		jbEdgesMoveUp = new javax.swing.JButton();
		jbEdgesMoveDown = new javax.swing.JButton();
		jpEdgeEditor = new javax.swing.JPanel();
		jlEdgeId = new javax.swing.JLabel();
		jtfEdgeId = new javax.swing.JTextField();
		jlBeginNodeId = new javax.swing.JLabel();
		jlEndNodeId = new javax.swing.JLabel();
		jtfBeginNodeId = new javax.swing.JTextField();
		jtfEndNodeId = new javax.swing.JTextField();
		jlOperation = new javax.swing.JLabel();
		jlOperationName = new javax.swing.JLabel();
		jtfOperationName = new javax.swing.JTextField();
		jlParameters = new javax.swing.JLabel();
		jspParameters = new javax.swing.JScrollPane();
		jtParameters = new javax.swing.JTable();
		jbParametersInsert = new javax.swing.JButton();
		jbParametersDelete = new javax.swing.JButton();
		jbParametersMoveUp = new javax.swing.JButton();
		jbParametersMoveDown = new javax.swing.JButton();
		jpSystemEditor = new javax.swing.JPanel();
		jlSystemName = new javax.swing.JLabel();
		jtfSystemName = new javax.swing.JTextField();
		jlSystemType = new javax.swing.JLabel();
		jrbSystemTypeInitial = new javax.swing.JRadioButton();
		jrbSystemTypeFinal = new javax.swing.JRadioButton();
		jrbSystemTypeRegular = new javax.swing.JRadioButton();
		jlObjects = new javax.swing.JLabel();
		jspObjects = new javax.swing.JScrollPane();
		jtObjects = new javax.swing.JTable();
		jbObjectsInsert = new javax.swing.JButton();
		jbObjectsDelete = new javax.swing.JButton();
		jbObjectsMoveUp = new javax.swing.JButton();
		jbObjectsMoveDown = new javax.swing.JButton();
		jspLinks = new javax.swing.JScrollPane();
		jtLinks = new javax.swing.JTable();
		jbLinksInsert = new javax.swing.JButton();
		jbLinksDelete = new javax.swing.JButton();
		jbLinksMoveUp = new javax.swing.JButton();
		jbLinksMoveDown = new javax.swing.JButton();
		jlLinks = new javax.swing.JLabel();
		jpObjectEditor = new javax.swing.JPanel();
		jlObjectName = new javax.swing.JLabel();
		jtfObjectName = new javax.swing.JTextField();
		jlObjectId = new javax.swing.JLabel();
		jtfObjectId = new javax.swing.JTextField();
		jlAttributes = new javax.swing.JLabel();
		jspAttributes = new javax.swing.JScrollPane();
		jtAttributes = new javax.swing.JTable();
		jbAttributesInsert = new javax.swing.JButton();
		jbAttributesDelete = new javax.swing.JButton();
		jbAttributesMoveUp = new javax.swing.JButton();
		jbAttributesMoveDown = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Node Network Editor");
		setName("jfNodeNetworkEditor"); // NOI18N

		javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Node Network");
		javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Nodes");
		javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("cad10712-45d4-4218-9e3c-2f5ac2eeaffa");
		javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("system");
		javax.swing.tree.DefaultMutableTreeNode treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece");
		treeNode4.add(treeNode5);
		treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("object-cylinder-surface");
		treeNode4.add(treeNode5);
		treeNode3.add(treeNode4);
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("0f45cf43-4ede-4ffc-adf6-6fe5ce6061cc");
		treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("system");
		treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece");
		treeNode4.add(treeNode5);
		treeNode5 = new javax.swing.tree.DefaultMutableTreeNode("object-cylinder-surface");
		treeNode4.add(treeNode5);
		treeNode3.add(treeNode4);
		treeNode2.add(treeNode3);
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Edges");
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("36685166-c73f-4a10-a99f-3e96b3d4bca0");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("bc8afd9f-8a68-4f09-b3a9-3ce7e67c6254");
		treeNode2.add(treeNode3);
		treeNode1.add(treeNode2);
		jtNodeNetwork.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
		jspNodeNetwork.setViewportView(jtNodeNetwork);

		jlNodeId.setText("id");

		jtfNodeId.setText("cad10712-45d4-4218-9e3c-2f5ac2eeaffa1");
		jtfNodeId.setToolTipText("");

		jcbChecked.setText("checked");

		jlEdges.setText("Edges");

		jtEdges.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "36685166-c73f-4a10-a99f-3e96b3d4bca0", "0f45cf43-4ede-4ffc-adf6-6fe5ce6061cc" },
						{ null, null }, { null, null }, { null, null } },
				new String[] { "id", "endNodeId" }) {
			private static final long serialVersionUID = 161486066590282479L;
			Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class };

			@Override
			public Class<?> getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jspEdges.setViewportView(jtEdges);

		jbEdgesInsert.setText("Insert");

		jbEdgesDelete.setText("Delete");

		jbEdgesMoveUp.setText("Up");

		jbEdgesMoveDown.setText("Down");

		javax.swing.GroupLayout jpNodeEditorLayout = new javax.swing.GroupLayout(jpNodeEditor);
		jpNodeEditor.setLayout(jpNodeEditorLayout);
		jpNodeEditorLayout.setHorizontalGroup(jpNodeEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpNodeEditorLayout.createSequentialGroup().addContainerGap()
						.addGroup(jpNodeEditorLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jpNodeEditorLayout.createSequentialGroup().addComponent(jlNodeId)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(jpNodeEditorLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jcbChecked).addComponent(jtfNodeId,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addComponent(jlEdges)
								.addComponent(jspEdges, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jbEdgesInsert).addComponent(jbEdgesDelete).addComponent(jbEdgesMoveUp)
								.addComponent(jbEdgesMoveDown))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpNodeEditorLayout.setVerticalGroup(jpNodeEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpNodeEditorLayout.createSequentialGroup().addContainerGap()
						.addGroup(jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlNodeId).addComponent(jtfNodeId, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jcbChecked)
						.addGap(18, 18, 18).addComponent(jlEdges)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								jpNodeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(jpNodeEditorLayout.createSequentialGroup().addComponent(jbEdgesInsert)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jbEdgesDelete)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jbEdgesMoveUp)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jbEdgesMoveDown))
										.addComponent(jspEdges, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
												Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jtpEditors.addTab("Node", jpNodeEditor);

		jlEdgeId.setText("id");

		jtfEdgeId.setText("36685166-c73f-4a10-a99f-3e96b3d4bca0");

		jlBeginNodeId.setText("beginNodeId");

		jlEndNodeId.setText("endNodeId");

		jtfBeginNodeId.setText("cad10712-45d4-4218-9e3c-2f5ac2eeaffa");

		jtfEndNodeId.setText("0f45cf43-4ede-4ffc-adf6-6fe5ce6061cc");

		jlOperation.setText("Operation");

		jlOperationName.setText("name");

		jtfOperationName.setText("operation-cut-cylinder-surface");

		jlParameters.setText("Parameters");

		jtParameters.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "parameter-diameter-delta", "2" }, { null, null }, { null, null }, { null, null } },
				new String[] { "name", "value" }) {
			private static final long serialVersionUID = -5501022587382142919L;
			Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class };

			@Override
			public Class<?> getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jspParameters.setViewportView(jtParameters);

		jbParametersInsert.setText("Insert");

		jbParametersDelete.setText("Delete");

		jbParametersMoveUp.setText("Up");

		jbParametersMoveDown.setText("Down");

		javax.swing.GroupLayout jpEdgeEditorLayout = new javax.swing.GroupLayout(jpEdgeEditor);
		jpEdgeEditor.setLayout(jpEdgeEditorLayout);
		jpEdgeEditorLayout.setHorizontalGroup(jpEdgeEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpEdgeEditorLayout.createSequentialGroup().addContainerGap().addGroup(jpEdgeEditorLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpEdgeEditorLayout.createSequentialGroup()
								.addGroup(jpEdgeEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jlOperationName).addComponent(jlOperation))
								.addGap(18, 18, 18).addComponent(jtfOperationName,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jpEdgeEditorLayout.createSequentialGroup()
								.addComponent(jspParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 207,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addGroup(jpEdgeEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jbParametersInsert).addComponent(jbParametersDelete)
										.addComponent(jbParametersMoveUp).addComponent(jbParametersMoveDown)))
						.addGroup(jpEdgeEditorLayout.createSequentialGroup().addComponent(jlEdgeId)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jtfEdgeId, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGroup(jpEdgeEditorLayout.createSequentialGroup()
								.addGroup(jpEdgeEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jlBeginNodeId).addComponent(jlEndNodeId))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jpEdgeEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addComponent(jtfBeginNodeId).addComponent(jtfEndNodeId)))
						.addComponent(jlParameters))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpEdgeEditorLayout.setVerticalGroup(jpEdgeEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpEdgeEditorLayout.createSequentialGroup().addContainerGap()
						.addGroup(jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlEdgeId).addComponent(jtfEdgeId, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addGroup(jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlBeginNodeId).addComponent(jtfBeginNodeId,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlEndNodeId).addComponent(jtfEndNodeId,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(32, 32, 32).addComponent(jlOperation)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpEdgeEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlOperationName).addComponent(jtfOperationName,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(18, 18, 18).addComponent(jlParameters)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpEdgeEditorLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jpEdgeEditorLayout.createSequentialGroup().addComponent(jbParametersInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbParametersDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbParametersMoveUp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbParametersMoveDown))
								.addComponent(jspParameters, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
										Short.MAX_VALUE))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jtpEditors.addTab("Edge", jpEdgeEditor);

		jlSystemName.setText("name");

		jtfSystemName.setText("system");

		jlSystemType.setText("type");

		jrbgSystemTypes.add(jrbSystemTypeInitial);
		jrbSystemTypeInitial.setText("initial");

		jrbgSystemTypes.add(jrbSystemTypeFinal);
		jrbSystemTypeFinal.setText("final");

		jrbgSystemTypes.add(jrbSystemTypeRegular);
		jrbSystemTypeRegular.setText("regular");

		jlObjects.setText("Objects");

		jtObjects
				.setModel(
						new javax.swing.table.DefaultTableModel(
								new Object[][] { { "object-workpiece", "8d36522c7-137d-4f18-b23a-23cefcf7663a" },
										{ "object-cylinder-surface", "85c6a5c3-a55b-4ce7-9278-2ecf019b6534" },
										{ null, null }, { null, null }, { null, null } },
								new String[] { "name", "id" }) {
							private static final long serialVersionUID = 363280195232090310L;
							Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class };

							@Override
							public Class<?> getColumnClass(int columnIndex) {
								return types[columnIndex];
							}
						});
		jspObjects.setViewportView(jtObjects);

		jbObjectsInsert.setText("Insert");

		jbObjectsDelete.setText("Delete");

		jbObjectsMoveUp.setText("Up");

		jbObjectsMoveDown.setText("Down");

		jtLinks.setModel(new javax.swing.table.DefaultTableModel(new Object[][] {
				{ "link-is-part-of", "8d3622c7-137d-4f18-b23a-23cefcf7663a", "85c6a5c3-255b-4ce7-9278-23cf019b6534" },
				{ null, null, null }, { null, null, null }, { null, null, null } },
				new String[] { "name", "id1", "id2" }) {
			private static final long serialVersionUID = 884462953158280826L;
			Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class };

			@Override
			public Class<?> getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jspLinks.setViewportView(jtLinks);

		jbLinksInsert.setText("Insert");

		jbLinksDelete.setText("Delete");

		jbLinksMoveUp.setText("Up");

		jbLinksMoveDown.setText("Down");

		jlLinks.setText("Links");

		javax.swing.GroupLayout jpSystemEditorLayout = new javax.swing.GroupLayout(jpSystemEditor);
		jpSystemEditor.setLayout(jpSystemEditorLayout);
		jpSystemEditorLayout.setHorizontalGroup(jpSystemEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpSystemEditorLayout.createSequentialGroup().addComponent(jlObjects).addGap(0, 0,
						Short.MAX_VALUE))
				.addGroup(jpSystemEditorLayout.createSequentialGroup().addGroup(jpSystemEditorLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpSystemEditorLayout.createSequentialGroup().addContainerGap()
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jlSystemType).addComponent(jlSystemName))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jtfSystemName, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGroup(jpSystemEditorLayout.createSequentialGroup()
												.addComponent(jrbSystemTypeInitial)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jrbSystemTypeFinal)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jrbSystemTypeRegular))))
						.addGroup(jpSystemEditorLayout.createSequentialGroup()
								.addComponent(jspObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 231,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jbObjectsInsert).addComponent(jbObjectsDelete)
										.addComponent(jbObjectsMoveUp).addComponent(jbObjectsMoveDown)))
						.addGroup(jpSystemEditorLayout.createSequentialGroup()
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jpSystemEditorLayout.createSequentialGroup().addContainerGap()
												.addComponent(jlLinks))
										.addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 232,
												javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jbLinksInsert).addComponent(jbLinksDelete)
										.addComponent(jbLinksMoveUp).addComponent(jbLinksMoveDown))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpSystemEditorLayout.setVerticalGroup(jpSystemEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpSystemEditorLayout.createSequentialGroup().addContainerGap()
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlSystemName).addComponent(jtfSystemName,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlSystemType).addComponent(jrbSystemTypeInitial)
								.addComponent(jrbSystemTypeFinal).addComponent(jrbSystemTypeRegular))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jlObjects)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jpSystemEditorLayout.createSequentialGroup().addComponent(jbObjectsInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbObjectsDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbObjectsMoveUp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbObjectsMoveDown))
								.addComponent(jspObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jlLinks)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jpSystemEditorLayout.createSequentialGroup().addComponent(jbLinksInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbLinksDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbLinksMoveUp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbLinksMoveDown)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jtpEditors.addTab("System", jpSystemEditor);

		jlObjectName.setText("name");

		jtfObjectName.setText("object-workpiece");

		jlObjectId.setText("id");

		jtfObjectId.setText("82d3622c7-137d-4f18-b23a-23cecfcf7663a");

		jlAttributes.setText("Attributes");

		jtAttributes
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { "attribute-workpiece", "boolean", "true" }, { null, null, null },
								{ null, null, null }, { null, null, null } },
						new String[] { "name", "type", "value" }) {
					private static final long serialVersionUID = -9221999499146745114L;
					Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class,
							java.lang.String.class };

					@Override
					public Class<?> getColumnClass(int columnIndex) {
						return types[columnIndex];
					}
				});
		jspAttributes.setViewportView(jtAttributes);

		jbAttributesInsert.setText("Insert");

		jbAttributesDelete.setText("Delete");

		jbAttributesMoveUp.setText("Up");

		jbAttributesMoveDown.setText("Down");

		javax.swing.GroupLayout jpObjectEditorLayout = new javax.swing.GroupLayout(jpObjectEditor);
		jpObjectEditor.setLayout(jpObjectEditorLayout);
		jpObjectEditorLayout.setHorizontalGroup(jpObjectEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpObjectEditorLayout.createSequentialGroup().addContainerGap().addGroup(jpObjectEditorLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpObjectEditorLayout.createSequentialGroup()
								.addComponent(jspAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 227,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jpObjectEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpObjectEditorLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jbAttributesInsert).addComponent(jbAttributesDelete)
												.addComponent(jbAttributesMoveUp))
										.addComponent(jbAttributesMoveDown,
												javax.swing.GroupLayout.Alignment.TRAILING)))
						.addGroup(jpObjectEditorLayout.createSequentialGroup()
								.addGroup(jpObjectEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(jlObjectId).addComponent(jlObjectName))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(jpObjectEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jtfObjectName, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(jtfObjectId, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
						.addComponent(jlAttributes))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpObjectEditorLayout.setVerticalGroup(jpObjectEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpObjectEditorLayout.createSequentialGroup().addContainerGap()
						.addGroup(jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlObjectName).addComponent(jtfObjectName,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jlObjectId).addComponent(jtfObjectId,
										javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addGap(32, 32, 32).addComponent(jlAttributes)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpObjectEditorLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jpObjectEditorLayout.createSequentialGroup().addComponent(jbAttributesInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbAttributesDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbAttributesMoveUp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbAttributesMoveDown))
								.addComponent(jspAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 0,
										Short.MAX_VALUE))
						.addContainerGap(118, Short.MAX_VALUE)));

		jtpEditors.addTab("Object", jpObjectEditor);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jspNodeNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 126,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtpEditors)));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jspNodeNetwork)
						.addGroup(layout.createSequentialGroup().addComponent(jtpEditors).addGap(22, 22, 22)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public static void initializeLookAndFeel() throws Exception {
		for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	}

	public static void main(String args[]) throws Exception {
		initializeLookAndFeel();
		SwingUtilities.invokeLater(() -> {
			new NodeNetworkEditorFrame().setVisible(true);
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbAttributesDelete;
	private javax.swing.JButton jbAttributesInsert;
	private javax.swing.JButton jbAttributesMoveDown;
	private javax.swing.JButton jbAttributesMoveUp;
	private javax.swing.JButton jbEdgesDelete;
	private javax.swing.JButton jbEdgesInsert;
	private javax.swing.JButton jbEdgesMoveDown;
	private javax.swing.JButton jbEdgesMoveUp;
	private javax.swing.JButton jbLinksDelete;
	private javax.swing.JButton jbLinksInsert;
	private javax.swing.JButton jbLinksMoveDown;
	private javax.swing.JButton jbLinksMoveUp;
	private javax.swing.JButton jbObjectsDelete;
	private javax.swing.JButton jbObjectsInsert;
	private javax.swing.JButton jbObjectsMoveDown;
	private javax.swing.JButton jbObjectsMoveUp;
	private javax.swing.JButton jbParametersDelete;
	private javax.swing.JButton jbParametersInsert;
	private javax.swing.JButton jbParametersMoveDown;
	private javax.swing.JButton jbParametersMoveUp;
	private javax.swing.JCheckBox jcbChecked;
	private javax.swing.JLabel jlAttributes;
	private javax.swing.JLabel jlBeginNodeId;
	private javax.swing.JLabel jlEdgeId;
	private javax.swing.JLabel jlEdges;
	private javax.swing.JLabel jlEndNodeId;
	private javax.swing.JLabel jlLinks;
	private javax.swing.JLabel jlNodeId;
	private javax.swing.JLabel jlObjectId;
	private javax.swing.JLabel jlObjectName;
	private javax.swing.JLabel jlObjects;
	private javax.swing.JLabel jlOperation;
	private javax.swing.JLabel jlOperationName;
	private javax.swing.JLabel jlParameters;
	private javax.swing.JLabel jlSystemName;
	private javax.swing.JLabel jlSystemType;
	private javax.swing.JPanel jpEdgeEditor;
	private javax.swing.JPanel jpNodeEditor;
	private javax.swing.JPanel jpObjectEditor;
	private javax.swing.JPanel jpSystemEditor;
	private javax.swing.JRadioButton jrbSystemTypeFinal;
	private javax.swing.JRadioButton jrbSystemTypeInitial;
	private javax.swing.JRadioButton jrbSystemTypeRegular;
	private javax.swing.ButtonGroup jrbgSystemTypes;
	private javax.swing.JScrollPane jspAttributes;
	private javax.swing.JScrollPane jspEdges;
	private javax.swing.JScrollPane jspLinks;
	private javax.swing.JScrollPane jspNodeNetwork;
	private javax.swing.JScrollPane jspObjects;
	private javax.swing.JScrollPane jspParameters;
	private javax.swing.JTable jtAttributes;
	private javax.swing.JTable jtEdges;
	private javax.swing.JTable jtLinks;
	private javax.swing.JTree jtNodeNetwork;
	private javax.swing.JTable jtObjects;
	private javax.swing.JTable jtParameters;
	private javax.swing.JTextField jtfBeginNodeId;
	private javax.swing.JTextField jtfEdgeId;
	private javax.swing.JTextField jtfEndNodeId;
	private javax.swing.JTextField jtfNodeId;
	private javax.swing.JTextField jtfObjectId;
	private javax.swing.JTextField jtfObjectName;
	private javax.swing.JTextField jtfOperationName;
	private javax.swing.JTextField jtfSystemName;
	private javax.swing.JTabbedPane jtpEditors;
	// End of variables declaration//GEN-END:variables

	// TODO (2022-08-28 #68): включить проверку copy-paste
	// CPD-OFF
}
