package application.ui.gui;

import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

public class TaskDescriptionEditorFrame extends javax.swing.JFrame {

	// TODO (2022-08-28 #68): включить проверку copy-paste
	// CPD-OFF

	private static final long serialVersionUID = -8192613140150379029L;

	public TaskDescriptionEditorFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jrbgSystemTypes = new javax.swing.ButtonGroup();
		jscpTaskDescription = new javax.swing.JScrollPane();
		jtTaskDescription = new javax.swing.JTree();
		jtpEditors = new javax.swing.JTabbedPane();
		jpSystemEditor = new javax.swing.JPanel();
		jtfSystemName = new javax.swing.JTextField();
		jlSystemName = new javax.swing.JLabel();
		jrbSystemTypeInitial = new javax.swing.JRadioButton();
		jrbSystemTypeFinal = new javax.swing.JRadioButton();
		jrbSystemTypeRegular = new javax.swing.JRadioButton();
		jspObjects = new javax.swing.JScrollPane();
		jtObjects = new javax.swing.JTable();
		jlObjects = new javax.swing.JLabel();
		jbObjectsInsert = new javax.swing.JButton();
		jbObjectsDelete = new javax.swing.JButton();
		jlSystemType = new javax.swing.JLabel();
		jbObjectsMoveUp = new javax.swing.JButton();
		jbObjectsMoveDown = new javax.swing.JButton();
		jlLinks = new javax.swing.JLabel();
		jspLinks = new javax.swing.JScrollPane();
		jtLinks = new javax.swing.JTable();
		jbLinksInsert = new javax.swing.JButton();
		jbLinksDelete = new javax.swing.JButton();
		jbLinksMoveUp = new javax.swing.JButton();
		jbLinksMoveDown = new javax.swing.JButton();
		jpObjectEditor = new javax.swing.JPanel();
		jtfObjectName = new javax.swing.JTextField();
		jlObjectName = new javax.swing.JLabel();
		jtfObjectId = new javax.swing.JTextField();
		jlObjectId = new javax.swing.JLabel();
		jspAttributes = new javax.swing.JScrollPane();
		jtAttributes = new javax.swing.JTable();
		jbAttributesInsert = new javax.swing.JButton();
		jbAttributesDelete = new javax.swing.JButton();
		jlAttributes = new javax.swing.JLabel();
		jbAttributesMoveUp = new javax.swing.JButton();
		jbAttributesMoveDown = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("Task Description Editor");
		setName("jfTaskDescriptionEditor"); // NOI18N

		javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode(
				"Task Description");
		javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode(
				"initialSystem");
		javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode(
				"object-workpiece");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-pad");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-pad-sketch");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-workpiece-plane");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pad");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pad-sketch");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part-plane");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket");
		treeNode2.add(treeNode3);
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket-sketch");
		treeNode2.add(treeNode3);
		treeNode1.add(treeNode2);
		treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("finalSystem");
		treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("object-part-pocket");
		treeNode2.add(treeNode3);
		treeNode1.add(treeNode2);
		jtTaskDescription.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
		jscpTaskDescription.setViewportView(jtTaskDescription);

		jtfSystemName.setText("initialSystem");

		jlSystemName.setText("name");

		jrbgSystemTypes.add(jrbSystemTypeInitial);
		jrbSystemTypeInitial.setSelected(true);
		jrbSystemTypeInitial.setText("initial");

		jrbgSystemTypes.add(jrbSystemTypeFinal);
		jrbSystemTypeFinal.setText("final");

		jrbgSystemTypes.add(jrbSystemTypeRegular);
		jrbSystemTypeRegular.setText("regular");

		jtObjects
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { "object-workpiece", "id-workpiece" },
								{ "object-workpiece-pad", "id-workpiece-pad" }, { null, null } },
						new String[] { "name", "id" }) {
					private static final long serialVersionUID = -3088616395233148837L;
					Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class };

					@Override
					public Class<?> getColumnClass(int columnIndex) {
						return types[columnIndex];
					}
				});
		jspObjects.setViewportView(jtObjects);

		jlObjects.setText("Objects");

		jbObjectsInsert.setText("Insert");

		jbObjectsDelete.setText("Delete");

		jlSystemType.setText("type");

		jbObjectsMoveUp.setText("Up");

		jbObjectsMoveDown.setText("Down");

		jlLinks.setText("Links");

		jtLinks.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { "link-has-feature", "id-part", "id-part-pad" },
						{ "link-has-feature", "id-workpiece", "id-workpiece-pad" }, { null, null, null },
						{ null, null, null }, { null, null, null } },
				new String[] { "name", "id1", "id2" }) {
			private static final long serialVersionUID = 7843667249897162662L;
			Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class, java.lang.String.class };

			@Override
			public Class<?> getColumnClass(int columnIndex) {
				return types[columnIndex];
			}
		});
		jspLinks.setViewportView(jtLinks);

		jbLinksInsert.setText("Insert");

		jbLinksDelete.setText("Delete");

		jbLinksMoveUp.setText("Up");

		jbLinksMoveDown.setText("Down");

		javax.swing.GroupLayout jpSystemEditorLayout = new javax.swing.GroupLayout(jpSystemEditor);
		jpSystemEditor.setLayout(jpSystemEditorLayout);
		jpSystemEditorLayout.setHorizontalGroup(jpSystemEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpSystemEditorLayout.createSequentialGroup().addGroup(jpSystemEditorLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpSystemEditorLayout.createSequentialGroup().addGap(12, 12, 12)
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jpSystemEditorLayout.createSequentialGroup()
												.addComponent(jlSystemName)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jtfSystemName, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGroup(jpSystemEditorLayout.createSequentialGroup()
												.addComponent(jlSystemType).addGap(18, 18, 18)
												.addComponent(jrbSystemTypeInitial)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jrbSystemTypeFinal)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jrbSystemTypeRegular))))
						.addGroup(jpSystemEditorLayout.createSequentialGroup().addContainerGap().addComponent(jlLinks))
						.addGroup(
								jpSystemEditorLayout.createSequentialGroup().addContainerGap().addComponent(jlObjects))
						.addGroup(jpSystemEditorLayout.createSequentialGroup().addGroup(jpSystemEditorLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
								.addComponent(jspLinks, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
								.addComponent(jspObjects, javax.swing.GroupLayout.Alignment.LEADING,
										javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jpSystemEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jpSystemEditorLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(jpSystemEditorLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(jpSystemEditorLayout
																.createParallelGroup(
																		javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jbObjectsInsert)
																.addComponent(jbObjectsDelete)
																.addComponent(jbObjectsMoveUp,
																		javax.swing.GroupLayout.Alignment.TRAILING))
														.addComponent(jbObjectsMoveDown,
																javax.swing.GroupLayout.Alignment.TRAILING))
												.addComponent(jbLinksInsert))
										.addComponent(jbLinksDelete).addComponent(jbLinksMoveUp)
										.addComponent(jbLinksMoveDown))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpSystemEditorLayout.setVerticalGroup(jpSystemEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSystemEditorLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jtfSystemName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jlSystemName))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jrbSystemTypeInitial).addComponent(jrbSystemTypeFinal)
								.addComponent(jrbSystemTypeRegular).addComponent(jlSystemType))
						.addGap(18, 18, 18).addComponent(jlObjects)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpSystemEditorLayout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addGroup(jpSystemEditorLayout.createSequentialGroup().addComponent(jbObjectsInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbObjectsDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbObjectsMoveUp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbObjectsMoveDown))
								.addComponent(jspObjects, javax.swing.GroupLayout.PREFERRED_SIZE, 106,
										javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jlLinks)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpSystemEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jspLinks, javax.swing.GroupLayout.PREFERRED_SIZE, 109,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jpSystemEditorLayout.createSequentialGroup().addComponent(jbLinksInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbLinksDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbLinksMoveUp)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbLinksMoveDown)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jtpEditors.addTab("System", jpSystemEditor);

		jtfObjectName.setText("object-workpiece");

		jlObjectName.setText("name");

		jtfObjectId.setText("id-workpiece");

		jlObjectId.setText("id");

		jtAttributes
				.setModel(new javax.swing.table.DefaultTableModel(
						new Object[][] { { "attribute-feature", "boolean", "true" }, { null, null, null },
								{ null, null, null }, { null, null, null } },
						new String[] { "name", "type", "value" }) {
					private static final long serialVersionUID = -1375888270764080577L;
					Class<?>[] types = new Class[] { java.lang.String.class, java.lang.String.class,
							java.lang.String.class };

					@Override
					public Class<?> getColumnClass(int columnIndex) {
						return types[columnIndex];
					}
				});
		jspAttributes.setViewportView(jtAttributes);

		jbAttributesInsert.setText("Insert");

		jbAttributesDelete.setText("Delete");

		jlAttributes.setText("Attributes");

		jbAttributesMoveUp.setText("Up");

		jbAttributesMoveDown.setText("Down");

		javax.swing.GroupLayout jpObjectEditorLayout = new javax.swing.GroupLayout(jpObjectEditor);
		jpObjectEditor.setLayout(jpObjectEditorLayout);
		jpObjectEditorLayout.setHorizontalGroup(jpObjectEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jpObjectEditorLayout.createSequentialGroup().addGroup(jpObjectEditorLayout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jpObjectEditorLayout
								.createSequentialGroup()
								.addGroup(jpObjectEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
										.addGroup(jpObjectEditorLayout.createSequentialGroup().addGap(25, 25, 25)
												.addGroup(jpObjectEditorLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jlObjectId).addComponent(jlObjectName))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addGroup(jpObjectEditorLayout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jtfObjectId).addComponent(jtfObjectName)))
										.addGroup(jpObjectEditorLayout.createSequentialGroup().addContainerGap()
												.addComponent(jspAttributes, javax.swing.GroupLayout.PREFERRED_SIZE,
														249, javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(jpObjectEditorLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jbAttributesInsert).addComponent(jbAttributesDelete)
										.addComponent(jbAttributesMoveUp).addComponent(jbAttributesMoveDown)))
						.addGroup(jpObjectEditorLayout.createSequentialGroup().addContainerGap()
								.addComponent(jlAttributes)))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		jpObjectEditorLayout.setVerticalGroup(jpObjectEditorLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpObjectEditorLayout.createSequentialGroup()
						.addGap(21, 21, 21)
						.addGroup(jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jtfObjectName, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jlObjectName))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jtfObjectId, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jlObjectId))
						.addGap(27, 27, 27).addComponent(jlAttributes)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(jpObjectEditorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jspAttributes, javax.swing.GroupLayout.PREFERRED_SIZE, 95,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGroup(jpObjectEditorLayout.createSequentialGroup().addComponent(jbAttributesInsert)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbAttributesDelete)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jbAttributesMoveUp).addGap(4, 4, 4)
										.addComponent(jbAttributesMoveDown)))
						.addContainerGap(121, Short.MAX_VALUE)));

		jtpEditors.addTab("Object", jpObjectEditor);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jscpTaskDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jtpEditors,
								javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addContainerGap(12, Short.MAX_VALUE).addComponent(jtpEditors,
						javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGroup(layout.createSequentialGroup().addComponent(jscpTaskDescription).addContainerGap()));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	public static void initializeLookAndFeel() throws Exception {
		for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
				UIManager.setLookAndFeel(info.getClassName());
				break;
			}
		}
	}

	public static void main(String args[]) throws Exception {
		initializeLookAndFeel();
		SwingUtilities.invokeLater(() -> {
			new TaskDescriptionEditorFrame().setVisible(true);
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jbAttributesDelete;
	private javax.swing.JButton jbAttributesInsert;
	private javax.swing.JButton jbAttributesMoveDown;
	private javax.swing.JButton jbAttributesMoveUp;
	private javax.swing.JButton jbLinksDelete;
	private javax.swing.JButton jbLinksInsert;
	private javax.swing.JButton jbLinksMoveDown;
	private javax.swing.JButton jbLinksMoveUp;
	private javax.swing.JButton jbObjectsDelete;
	private javax.swing.JButton jbObjectsInsert;
	private javax.swing.JButton jbObjectsMoveDown;
	private javax.swing.JButton jbObjectsMoveUp;
	private javax.swing.JLabel jlAttributes;
	private javax.swing.JLabel jlLinks;
	private javax.swing.JLabel jlObjectId;
	private javax.swing.JLabel jlObjectName;
	private javax.swing.JLabel jlObjects;
	private javax.swing.JLabel jlSystemName;
	private javax.swing.JLabel jlSystemType;
	private javax.swing.JPanel jpObjectEditor;
	private javax.swing.JPanel jpSystemEditor;
	private javax.swing.JRadioButton jrbSystemTypeFinal;
	private javax.swing.JRadioButton jrbSystemTypeInitial;
	private javax.swing.JRadioButton jrbSystemTypeRegular;
	private javax.swing.ButtonGroup jrbgSystemTypes;
	private javax.swing.JScrollPane jscpTaskDescription;
	private javax.swing.JScrollPane jspAttributes;
	private javax.swing.JScrollPane jspLinks;
	private javax.swing.JScrollPane jspObjects;
	private javax.swing.JTable jtAttributes;
	private javax.swing.JTable jtLinks;
	private javax.swing.JTable jtObjects;
	private javax.swing.JTree jtTaskDescription;
	private javax.swing.JTextField jtfObjectId;
	private javax.swing.JTextField jtfObjectName;
	private javax.swing.JTextField jtfSystemName;
	private javax.swing.JTabbedPane jtpEditors;
	// End of variables declaration//GEN-END:variables

	// TODO (2022-08-28 #68): включить проверку copy-paste
	// CPD-OFF
}
